name: CI Diff-quality

on:
    push:
        branches:
            - diff-quality
env:
  DBT_DEFAULT_PROFILE_TARGET: stellar_dbt_public
  DBT_PROFILES_DIR: ${{ github.workspace }}
  DBT_TARGET: prod
  DBT_MAX_BYTES_BILLED: 1000000000000
  DBT_JOB_TIMEOUT: 300
  DBT_THREADS: 1
  DBT_JOB_RETRIES: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        dbt deps
      
    - name: Authenticate to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: crypto-stellar   
        credentials_json: "${{ secrets.CREDS_PROD_HUBBLE }}" 

    # - name: Set up dbt profile
    #   run: |
    #     . ci_profiles.sh

    - name: Checkout source branch and diff quality
      run:  |
        git checkout ${{ github.ref_name }}
        dbt docs generate
        diff-quality --violations=sqlfluff --fail-under=95 --compare-branch=origin/master